//////////////////////////////////////////////////////////////////////
// C++ source file generated by SCRC V2.1
// Design: gps_stim
// File:   gps_stim.cc
// Time:   Sat May  2 16:28:51 2015
//////////////////////////////////////////////////////////////////////

#include "gps_stim.h"

// behavior class definitions ////////////////////////////////////////

GPS_stim::GPS_stim(i_sender (&gps_raw), const char *(&file_name))
    : gps_raw(gps_raw), file_name(file_name)
{   /* nothing */
}

GPS_stim::~GPS_stim(void)
{   /* nothing */
}

#line 8 "gps_stim.sc"
void GPS_stim::main(void) {

    struct _IO_FILE *fin;
    unsigned int timestamp;
    double latitude; double longitude;
    char ew; char ns;
    struct gps_send_data_t sd;

    fin = fopen(file_name, "r");

    if (fin == ((void *)0)) {
	printf("GPS Input File Missing!\n");
	return ;
    }

    while(1) {
	if (fscanf(fin, "%u,%lf,%c,%lf,%c\n",  &timestamp,  &latitude,  &ns,  &longitude,  &ew) == ( -1))
	    break;

	sd.ts = timestamp;
	sd.lat = latitude;
	sd.ns = ns;
	sd.lon = longitude;
	sd.ew = ew;

	gps_raw.send( &sd, sizeof (sd));
    }
}

//////////////////////////////////////////////////////////////////////
// End of file gps_stim.cc
//////////////////////////////////////////////////////////////////////
